### Test my Task Tracker Backend
GET https://tasktracker-4pc3.onrender.com/db-test

### Create a New Task
POST https://tasktracker-4pc3.onrender.com/tasks
Content-Type: application/json

{
    "title": "Debug Render Connection",
    "description": "Verify the POST route is working with Clever Cloud",
    "priority": "high"
}